import { styled } from "..";

export const HeaderContainer = styled("header", {
  padding: "2rem 0",
  width: "100%",
  maxWidth: "86%",
  margin: "0 auto",
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  ".buttonContainer": {
    position: "relative",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    span: {
      position: "absolute",
      zIndex: 2,
      bottom: 7,
      left: 7,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "1.5rem",
      height: "1.5rem",
      background: "$green500",
      border: "3px solid $gray900",
      borderRadius: "50%",
      p: {
      fontWeight: 700,
      fontSize: "0.875rem",
      color: "$white",
      },
    },
    button: {
      position: "absolute",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: 12,
      borderRadius: 6,
      background: "$gray800",
      border: "none",
      cursor: "pointer",
      "&:hover": {
        filter: "brightness(0.7)",
      },
      svg: {
        fontSize: 24,
        color: "$gray600",
      },
    },
  },
});

export const HeaderContainerTwo = styled("header", {
  padding: "2rem 0",
  width: "100%",
  maxWidth: "86%",
  margin: "0 auto",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
});

export const Container = styled("div", {
  display: "flex",
  width: "100%",
  ".modal": {
    width: "100%",
    position: "absolute",
    zIndex: 2,
    top: 0,
    left: 0,
    minHeight: "100vh",
    background: "rgba(212, 221, 255, 0)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ".modalContent": {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      marginLeft: "auto",
      background: "$gray800",
      minHeight: "100vh",
      padding: "3rem",
      width: "32rem",
      gap: "1rem",
      boxShadow: "-4px 0px 30px rgba(0, 0, 0, 0.8)",
      ".wrappperOne": {
        ".alert": {
        marginTop: '6rem',
        display: "flex",
        alignItems: 'center',
        flexDirection: "column",
        justifyContent: "center",
        gap: '2rem',
        h1: {
          fontSize: '2rem',
          fontStyle: 'italic',
        },
        svg: {
          fontSize: '8rem',
        },
      }
      },
      ".close": {
        position: "absolute",
        color: "$gray600",
        top: "3rem",
        right: "3rem",
        background: "none",
        border: "none",
        cursor: "pointer",
        fontSize: "1.5rem",
        "&:hover": {
          filter: "brightness(0.7)",
        },
      },
      h1: {
        fontFamily: "Roboto",
        fontWeight: 700,
        fontSize: 20,
        lineheight: 1.6,
        display: "flex",
        alignItems: "center",
        color: "$gray100",
        marginTop: "1rem",
      },
      ".items": {
        display: "flex",
        flexDirection: "column",
        gap: "1.5rem",
        marginTop: "2rem",
        maxHeight: 358,
        overflow: "auto",
        "&::-webkit-scrollbar": {
          width: 15,
        },
        "&::-webkit-scrollbar-thumb": {
          background: "$green300",
          borderRadius: 10,
          width: 0,
          backgroundClip: "padding-box",
          border: "3px solid transparent",
        },
        "&::-webkit-scrollbar-thumb:hover": {
          backgroundColor: "$green500",
          width: 0,
          borderRadius: 10,
          backgroundClip: "padding-box",
          border: "3px solid transparent",
        },
      },
      ".item": {
        display: "flex",
        alignItems: "center",
        gap: "1.25rem",
        ".image": {
          display: "flex",
          alignItem: "center",
          justifyContent: "center",
          background: "linear-gradient(180deg, #1ea483 0%, #7465d4 100%)",
          borderRadius: "0.5rem",
          width: "6.3rem",
        },
        ".details": {
          display: "flex",
          flexDirection: "column",
          gap: 2,
          span: {
            fontWeight: 400,
            fontSize: 18,
            lineHeight: 1.6,
            color: "$gray300",
            whiteSpace: 'nowrap',
          },
          strong: {
            fontFamily: "Roboto",
            fontSize: 18,
            lineHeight: 1.6,
            display: "flex",
            alignItems: "center",
            color: "$gray100",
          },
        },
        button: {
          marginTop: "0.5rem",
          width: 65,
          height: 26,
          fontFamily: "Roboto",
          fontStyle: "normal",
          fontWeight: 700,
          fontSize: 16,
          lineHeight: 1.6,
          color: "$green500",
          cursor: "pointer",
          border: 0,
          background: "none",
          "&:hover": {
            filter: "brightness(0.7)",
          },
        },
      },
      ".amounts": {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "0.5rem",
        "span:nth-child(1)": {
          fontSize: "1rem",
          lineHeight: 1.6,
          display: "flex",
          alignItems: "center",
          color: "$gray100",
        },
        "span:nth-child(2)": {
          fontSize: "1.125rem",
          lineHeight: 1.6,
          display: "flex",
          alignItems: "center",
          color: "$gray300",
        },
      },
      ".total": {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "0.5rem",
        "strong:nth-child(1)": {
          fontWeight: 700,
          fontSize: "1.125rem",
          lineHeight: 1.6,
          display: "flex",
          alignItems: "center",
          color: "$gray100",
        },
        "strong:nth-child(2)": {
          fontSize: "1.5rem",
          lineHeight: 1.4,
          display: "flex",
          alignItems: "center",
          color: "$gray100",
        },
      },
      ".buy": {
        width: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        border: 0,
        padding: 20,
        gap: 10,
        background: "$green500",
        borderRadius: 8,
        fontWeight: 700,
        fontSize: "1.125rem",
        lineHeight: 1.6,
        color: "$white",
        cursor: "pointer",
        "&:disabled": {
          opacity: 0.6,
          cursor: "not-allowed",
        },
    
        "&:not(:disabled):hover": {
          backgroundColor: "$green300",
        },
      },
    },
  },
  ".none": {
    display: "none",
  },
});
